services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - ./web:/app
    env_file:
      - ./web/.env.dev
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/.env.dev
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/backup-createx.sql:/backup-createx.sql
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  db:
